data_dir = "/var/lib/vector"

[sources.apache_logs]
  ignore_older = 86400
  include = ["/var/log/apache2/*.log"]
  type = "file"

[transforms.apache_lua]
  inputs = [ ]
  type = "lua"
  version = "2"
  [transforms.apache_lua.hooks]
    process = "function (event, emit)\n  -- event.log.field = \"value\" -- set value of a field\n  -- event.log.another_field = nil -- remove field\n  -- event.log.first, event.log.second = nil, event.log.first -- rename field\n\n  -- Very important! Emit the processed event.\n  emit(event)\nend\n"

[transforms.apache_parser]
  drop_on_error = false
  inputs = ["apache_logs"]
  source = ". |= parse_regex!(.message, r'^(?P<host>[\\w.]+) - (?P<user>[\\w]+) (?P<bytes_in>[\\d]+) [(?P<timestamp>.*)] \"(?P<method>[\\w]+) (?P<path>.*)\" (?P<status>[\\d]+) (?P<bytes_out>[\\d]+)$'),\n"
  type = "remap"

[transforms.apache_sampler]
  inputs = ["apache_parser"]
  rate = 50
  type = "sample"

[transforms.log_to_metric]
  inputs = ["apache_parser"]
  type = "log_to_metric"
  [[transforms.log_to_metric.metrics]]
    field = "message"
    type = "counter"
  [[transforms.log_to_metric.metrics]]
    field = "bytes_out"
    increment_by_value = true
    name = "bytes_out_total"
    type = "counter"
  [[transforms.log_to_metric.metrics]]
    field = "bytes_out"
    type = "gauge"
  [[transforms.log_to_metric.metrics]]
    field = "user"
    type = "set"
  [[transforms.log_to_metric.metrics]]
    field = "bytes_out"
    name = "bytes_out_histogram"
    type = "histogram"

[sinks.es_cluster]
  host = "http://79.12.221.222:9200"
  index = "vector-%Y-%m-%d"
  inputs = ["apache_sampler"]
  type = "elasticsearch"

[sinks.prometheus]
  buckets = [0, 10, 100, 1000, 10000, 100001]
  default_namespace = "vector"
  inputs = ["log_to_metric"]
  type = "prometheus_exporter"

[sinks.s3_archives]
  bucket = "my-log-archives"
  compression = "gzip"
  encoding = "ndjson"
  inputs = ["apache_parser"]
  key_prefix = "date=%Y-%m-%d"
  region = "us-east-1"
  type = "aws_s3"
  [sinks.s3_archives.batch]
    max_size = 10000000


